version: '3'

services:

  database:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      #Modify following line
      - ./database.sqlite:/root/db/database.sqlite
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    restart: unless-stopped

volumes:
###> doctrine/doctrine-bundle ###
  database:
###< doctrine/doctrine-bundle ###
